[metadata]
addr = 27990
size = 93
last_change = 1660445255

[header]
last_change = 1660445255
name = "sub_6D56"
addr = 27990
ret_type = "long"

[stack_vars.0]
last_change = 1660445229
stack_offset = 0
stack_offset_type = 1
name = "regs"
type = "struct user_regs_struct"
size = 216
addr = 27990

[header.args.0]
idx = 0
name = "pid"
type_str = "long"
size = 8

[header.args.1]
idx = 1
name = "regs"
type_str = "struct user_regs_struct *"
size = 8
