[metadata]
addr = 62126
size = 403
last_change = 1660453629

[header]
last_change = 1660449455
name = "sub_F2AE"
addr = 62126
ret_type = "long"

[stack_vars.-10]
last_change = 1660449782
stack_offset = -16
stack_offset_type = 1
name = "cookie"
type = "unsigned long"
size = 8
addr = 62126

[stack_vars.-e8]
last_change = 1660453629
stack_offset = -232
stack_offset_type = 1
name = "v4"
type = "long[28]"
size = 224
addr = 62126

[header.args.0]
idx = 0
name = "a1"
type_str = "long"
size = 8

[header.args.1]
idx = 1
name = "a2"
type_str = "struct mystruct *"
size = 8
