[metadata]
addr = 15654
size = 667
last_change = 1660443717

[header]
last_change = 1660443717
name = "sub_3D26"
addr = 15654
ret_type = "long"

[stack_vars.-e8]
last_change = 1660443061
stack_offset = -232
stack_offset_type = 1
name = "v6"
type = "struct user_regs_struct"
size = 216
addr = 15654

[header.args.0]
idx = 0
name = "pid_ptr"
type_str = "__pid_t *"
size = 8
