[metadata]
addr = 15654
size = 667
last_change = 1660448585

[header]
last_change = 1660448585
name = "important_shit"
addr = 15654

[stack_vars.-e8]
last_change = 1660443756
stack_offset = -232
stack_offset_type = 1
name = "regs"
type = "struct user_regs_struct"
size = 216
addr = 15654
