[metadata]
addr = 29435
size = 1420

[header]
last_change = 1660501021
name = "handler_exec"
addr = 29435

[stack_vars.-128]
last_change = 1660441681
stack_offset = -296
stack_offset_type = 1
name = "v18"
type = "long[31]"
size = 248
addr = 29435
