[metadata]
addr = 29435
size = 1420
last_change = 1660441663

[stack_vars.-128]
last_change = 1660441663
stack_offset = -296
stack_offset_type = 1
name = "a3"
type = "long[31]"
size = 248
addr = 29435
