[metadata]
addr = 29435
size = 1420
last_change = 1660453627

[stack_vars.-128]
last_change = 1660441681
stack_offset = -296
stack_offset_type = 1
name = "v18"
type = "long[31]"
size = 248
addr = 29435

[stack_vars.-958]
last_change = 1660453627
stack_offset = -2392
stack_offset_type = 1
name = "v15"
type = "char[16]"
size = 16
addr = 29435
