[metadata]
addr = 10620
size = 96
last_change = 1660449557

[header]
last_change = 1660449557
name = "u_ptrace_getregs"
addr = 10620
ret_type = "long"

[header.args.0]
idx = 0
name = "a1"
type_str = "struct mystruct *"
size = 8

[header.args.1]
idx = 1
name = "a2"
type_str = "struct ptregs_struct *"
size = 8
