[metadata]
addr = 27990
size = 93
last_change = 1660445225

[stack_vars.0]
last_change = 1660445225
stack_offset = 0
stack_offset_type = 1
name = "regs"
type = "struct user_regs_struct"
size = 216
addr = 27990
