[metadata]
addr = 28083
size = 326
last_change = 1660453627

[stack_vars.-f0]
last_change = 1660453627
stack_offset = -240
stack_offset_type = 1
name = "v6"
type = "unsigned int *"
size = 8
addr = 28083
