[metadata]
addr = 15028
size = 626
last_change = 1660449646

[header]
last_change = 1660449493
name = "sub_3AB4"
addr = 15028
ret_type = "long"

[stack_vars.-e8]
last_change = 1660449535
stack_offset = -232
stack_offset_type = 1
name = "regs"
type = "struct user_regs_struct"
size = 216
addr = 15028

[header.args.0]
idx = 0
name = "a1"
type_str = "struct mystruct *"
size = 8

[header.args.1]
idx = 1
name = "a2"
type_str = "long"
size = 8
