[metadata]
addr = 15028
size = 626
last_change = 1660439208

[header]
last_change = 1660439208
name = "sub_3AB4"
addr = 15028
ret_type = "long"

[header.args.0]
idx = 0
name = "a1"
type_str = "unsigned long"
size = 8
