[metadata]
addr = 62126
size = 403

[header]
last_change = 1660449455
name = "sub_F2AE"
addr = 62126
ret_type = "long"

[stack_vars.-e8]
last_change = 1671592557
stack_offset = -232
stack_offset_type = 1
name = "a2"
type = "long[28]"
size = 224
addr = 62126

[header.args.0]
idx = 0
name = "a1"
type_str = "long"
size = 8

[header.args.1]
idx = 1
name = "a2"
type_str = "struct mystruct *"
size = 8
