[metadata]
addr = 62126
size = 403

[stack_vars.-10]
last_change = 1660449782
stack_offset = -16
stack_offset_type = 1
name = "cookie"
type = "unsigned long"
size = 8
addr = 62126

[stack_vars.-e8]
last_change = 1671592557
stack_offset = -232
stack_offset_type = 1
name = "a2"
type = "long[28]"
size = 224
addr = 62126
