[metadata]
addr = 60322
size = 144

[header]
last_change = 1660453498
name = "resolved_path"
addr = 60322
ret_type = "unsigned long"

[stack_vars.-10]
last_change = 1660457999
stack_offset = -16
stack_offset_type = 1
name = "_canary"
type = "unsigned long"
size = 8
addr = 60322

[header.args.0]
idx = 0
name = "output_path"
type_str = "char **"
size = 8

[header.args.1]
idx = 1
name = "input_path"
type_str = "const char *"
size = 8
