[metadata]
addr = 14778
size = 186
last_change = 1660449323

[header]
last_change = 1660449323
name = "sub_39BA"
addr = 14778
ret_type = "long"

[header.args.0]
idx = 0
name = "a1"
type_str = "struct mystruct *"
size = 8
