[metadata]
addr = 9822
size = 264
last_change = 1660449065

[header]
last_change = 1660449065
name = "sub_265E"
addr = 9822
ret_type = "unsigned long"

[header.args.0]
idx = 0
name = "mystruct"
type_str = "long"
size = 8
