[metadata]
addr = 86806
size = 814
last_change = 1660462344

[header]
last_change = 1660430784
name = "main"
addr = 86806
ret_type = "long"

[stack_vars.-a0]
last_change = 1660453629
stack_offset = -160
stack_offset_type = 1
name = "v11"
type = "char *"
size = 8
addr = 86806

[header.args.0]
idx = 0
name = "argc"
type_str = "int"
size = 4

[header.args.1]
idx = 1
name = "argv"
type_str = "char **"
size = 8

[header.args.2]
idx = 2
name = "a3"
type_str = "char **"
size = 8
