[metadata]
addr = 94841
size = 165
last_change = 1677460611

[stack_vars.-78]
last_change = 1677460611
stack_offset = -120
stack_offset_type = 1
name = "a1"
type = "_DWORD[26]"
size = 104
addr = 94841
