[metadata]
addr = 86806
size = 814
last_change = 1660441319

[stack_vars.-90]
last_change = 1660441319
stack_offset = -144
stack_offset_type = 1
name = "resolved_rootpath"
type = "char **"
size = 8
addr = 86806
