[metadata]
addr = 86806
size = 814
last_change = 1671391554

[stack_vars.-78]
last_change = 1671391554
stack_offset = -120
stack_offset_type = 1
name = "a1"
type = "char[88]"
size = 88
addr = 86806

[stack_vars.-80]
last_change = 1660441691
stack_offset = -128
stack_offset_type = 1
name = "a2"
type = "long"
size = 8
addr = 86806
