[metadata]
name = "__va_list_tag"
size = 8
last_change = 1660500888

[members.0]
member_name = "gp_offset"
offset = 0
type = "unsigned int"
size = 4

[members.4]
member_name = "fp_offset"
offset = 4
type = ""
size = 4
