[metadata]
name = "__va_list_tag"
size = 16
last_change = 1660441599

[members.0]
member_name = "gp_offset"
offset = 0
type = "unsigned int"
size = 4

[members.4]
member_name = "fp_offset"
offset = 4
type = "unsigned int"
size = 4

[members.8]
member_name = "overflow_arg_area"
offset = 8
type = ""
size = 8
