[metadata]
name = "gcc_va_list"
size = 16

[members.0]
member_name = "gp_offset"
offset = 0
type = "unsigned int"
size = 4

[members.4]
member_name = "fp_offset"
offset = 4
type = "unsigned int"
size = 4

[members.8]
member_name = "overflow_arg_area"
offset = 8
type = ""
size = 8
