[metadata]
name = "mystruct"
size = 21
last_change = 1660448955

[members.0]
member_name = "field_0"
offset = 0
type = ""
size = 4

[members.4]
member_name = "field_4"
offset = 4
type = ""
size = 8

[members.c]
member_name = "field_C"
offset = 12
type = ""
size = 8

[members.14]
member_name = "field_14"
offset = 20
type = ""
size = 1
