[metadata]
name = "mystruct"
size = 76
last_change = 1660449138

[members.0]
member_name = "pid"
offset = 0
type = ""
size = 4

[members.4]
member_name = "field_4"
offset = 4
type = ""
size = 8

[members.c]
member_name = "field_C"
offset = 12
type = ""
size = 8

[members.14]
member_name = "field_14"
offset = 20
type = ""
size = 8

[members.1c]
member_name = "field_1C"
offset = 28
type = ""
size = 8

[members.24]
member_name = "field_24"
offset = 36
type = ""
size = 8

[members.2c]
member_name = "field_2C"
offset = 44
type = ""
size = 8

[members.34]
member_name = "field_34"
offset = 52
type = ""
size = 8

[members.3c]
member_name = "field_3C"
offset = 60
type = ""
size = 1

[members.3d]
member_name = "field_3D"
offset = 61
type = ""
size = 1

[members.3e]
member_name = "field_3E"
offset = 62
type = ""
size = 1

[members.3f]
member_name = "field_3F"
offset = 63
type = ""
size = 8

[members.48]
member_name = "field_48"
offset = 72
type = ""
size = 4
