[metadata]
name = "mystruct"
size = 75
last_change = 1660449159

[members.0]
member_name = "pid"
offset = 0
type = ""
size = 4

[members.4]
member_name = "field_4"
offset = 4
type = ""
size = 4

[members.8]
member_name = "field_8"
offset = 8
type = ""
size = 4

[members.c]
member_name = "field_C"
offset = 12
type = ""
size = 4

[members.10]
member_name = "field_10"
offset = 16
type = ""
size = 4

[members.14]
member_name = "field_14"
offset = 20
type = ""
size = 4

[members.18]
member_name = "field_18"
offset = 24
type = ""
size = 4

[members.1c]
member_name = "field_1C"
offset = 28
type = ""
size = 4

[members.20]
member_name = "field_20"
offset = 32
type = ""
size = 2

[members.24]
member_name = "field_24"
offset = 36
type = ""
size = 8

[members.2c]
member_name = "field_2C"
offset = 44
type = ""
size = 8

[members.34]
member_name = "field_34"
offset = 52
type = ""
size = 8

[members.3c]
member_name = "field_3C"
offset = 60
type = ""
size = 2

[members.3e]
member_name = "field_3E"
offset = 62
type = ""
size = 2

[members.47]
member_name = "field_47"
offset = 71
type = ""
size = 4
