[metadata]
name = "mystruct"
size = 176
last_change = 1660449038

[members.0]
member_name = "field_0"
offset = 0
type = ""
size = 4

[members.4]
member_name = "field_4"
offset = 4
type = ""
size = 8

[members.c]
member_name = "field_C"
offset = 12
type = ""
size = 8

[members.14]
member_name = "field_14"
offset = 20
type = ""
size = 8

[members.1c]
member_name = "field_1C"
offset = 28
type = ""
size = 8

[members.24]
member_name = "field_24"
offset = 36
type = ""
size = 8

[members.2c]
member_name = "field_2C"
offset = 44
type = ""
size = 8

[members.34]
member_name = "field_34"
offset = 52
type = ""
size = 8

[members.3c]
member_name = "field_3C"
offset = 60
type = ""
size = 8

[members.44]
member_name = "field_44"
offset = 68
type = ""
size = 4

[members.64]
member_name = "field_64"
offset = 100
type = ""
size = 8

[members.6c]
member_name = "field_6C"
offset = 108
type = ""
size = 8

[members.74]
member_name = "field_74"
offset = 116
type = ""
size = 8

[members.7c]
member_name = "field_7C"
offset = 124
type = ""
size = 8

[members.84]
member_name = "field_84"
offset = 132
type = ""
size = 8

[members.8c]
member_name = "field_8C"
offset = 140
type = ""
size = 8

[members.94]
member_name = "field_94"
offset = 148
type = ""
size = 8

[members.9c]
member_name = "field_9C"
offset = 156
type = ""
size = 8

[members.a4]
member_name = "field_A4"
offset = 164
type = ""
size = 8

[members.ac]
member_name = "field_AC"
offset = 172
type = ""
size = 4
