[metadata]
name = "user_regs_struct"
size = 16
last_change = 1660443016

[members.0]
member_name = "_r15"
offset = 0
type = "unsigned long"
size = 8

[members.8]
member_name = "_r14"
offset = 8
type = ""
size = 8
