[metadata]
name = "user_regs_struct"
size = 32
last_change = 1660443017

[members.0]
member_name = "_r15"
offset = 0
type = "unsigned long"
size = 8

[members.8]
member_name = "_r14"
offset = 8
type = "unsigned long"
size = 8

[members.10]
member_name = "_r13"
offset = 16
type = "unsigned long"
size = 8

[members.18]
member_name = "_r12"
offset = 24
type = ""
size = 8
